version: '3.7'

services:
  hello-world-with-docker:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/projects/hello-world/src
    container_name: hello-world-with-docker
    
    command: npm run run